### PR TITLE
Things rjbs and I discussed

### PR DESCRIPTION
**Pull request by exodist**
- context_do
- context_sub
- aquire hook so that Test::Builder can make $Level work everywhere

### CODE REVIEW

**Comment by rjbs** [comment]
You want "ensure" and not "insure."  Generally to "ensure" is to make sure something happens, and to "insure" is to do that thing where you promise to pay somebody if something breaks. :-)

**Comment by rjbs** [comment]
I think context_sub is too much.  That is:

It's only going to be needed very occasionally, at most, when writing libraries.  It's magical enough that people will need to think about to use it, and then by the next time they use it, they may well have forgotten.  Its benefits are pretty low, the complexity is kinda high, and it's more choices.  More choices means more thinking, and nothing is worse for writing good code than _thinking_.

I'd leave it out, if I were you.

**Comment by rjbs** [comment]
That context-acquisition callback -- presumably there's a matching change in Test::Builder to use it?  (My computer is all messed up now, so I can't easily fetch branches.)

**Comment by exodist** [comment]
Yes, there is a change to Test::Builder to use the hook.

I will fix the typo.

I will remove context_sub. I may split it into its own dist, or I may not bother.

**Pull request closed without merging**
